apiVersion: v1
kind: Secret
metadata:
  name: kubecost-federated-store
  namespace: kubecost
type: Opaque
stringData:
  federated-store.yaml: |
    type: S3
    config:
      bucket: "pd-geodowd-kubecost-cost-data"
      endpoint: "s3.amazonaws.com"
      region: "eu-west-1"
